class ServerModel {
  final String id;
  final String name;
  final String country;
  final String countryCode;
  final String city;
  final String flagEmoji;
  final int pingMs;
  final int loadPercent;
  final bool isPremium;
  final String endpoint; // e.g. 192.0.2.1:51820
  final String publicKey;
  final String privateKey;
  final String allowedIps;
  final String? clientIpv4;
  final bool isFavorite;

  const ServerModel({
    required this.id,
    required this.name,
    required this.country,
    required this.countryCode,
    required this.city,
    required this.flagEmoji,
    required this.pingMs,
    required this.loadPercent,
    required this.isPremium,
    required this.endpoint,
    required this.publicKey,
    required this.privateKey,
    this.allowedIps = '0.0.0.0/0',
    this.clientIpv4 = '10.8.0.2/32',
    this.isFavorite = false,
  });

  ServerModel copyWith({
    String? id,
    String? name,
    String? country,
    String? countryCode,
    String? city,
    String? flagEmoji,
    int? pingMs,
    int? loadPercent,
    bool? isPremium,
    String? endpoint,
    String? publicKey,
    String? privateKey,
    String? allowedIps,
    String? clientIpv4,
    bool? isFavorite,
  }) {
    return ServerModel(
      id: id ?? this.id,
      name: name ?? this.name,
      country: country ?? this.country,
      countryCode: countryCode ?? this.countryCode,
      city: city ?? this.city,
      flagEmoji: flagEmoji ?? this.flagEmoji,
      pingMs: pingMs ?? this.pingMs,
      loadPercent: loadPercent ?? this.loadPercent,
      isPremium: isPremium ?? this.isPremium,
      endpoint: endpoint ?? this.endpoint,
      publicKey: publicKey ?? this.publicKey,
      privateKey: privateKey ?? this.privateKey,
      allowedIps: allowedIps ?? this.allowedIps,
      clientIpv4: clientIpv4 ?? this.clientIpv4,
      isFavorite: isFavorite ?? this.isFavorite,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'country': country,
      'countryCode': countryCode,
      'city': city,
      'flagEmoji': flagEmoji,
      'pingMs': pingMs,
      'loadPercent': loadPercent,
      'isPremium': isPremium,
      'endpoint': endpoint,
      'publicKey': publicKey,
      'privateKey': privateKey,
      'allowedIps': allowedIps,
      'clientIpv4': clientIpv4,
      'isFavorite': isFavorite,
    };
  }

  factory ServerModel.fromJson(Map<String, dynamic> json) {
    return ServerModel(
      id: json['id'] as String,
      name: json['name'] as String,
      country: json['country'] as String,
      countryCode: json['countryCode'] as String? ?? 'UN',
      city: json['city'] as String,
      flagEmoji: json['flagEmoji'] as String? ?? '🌐',
      pingMs: (json['pingMs'] as num?)?.toInt() ?? 80,
      loadPercent: (json['loadPercent'] as num?)?.toInt() ?? 45,
      isPremium: json['isPremium'] as bool? ?? false,
      endpoint: json['endpoint'] as String? ?? '192.0.2.1:51820',
      publicKey: json['publicKey'] as String? ?? 'bm8tcHVibGljLWtleS1wcm92aWRlZA==',
      privateKey: json['privateKey'] as String? ?? '',
      allowedIps: json['allowedIps'] as String? ?? '0.0.0.0/0',
      clientIpv4: json['clientIpv4'] as String? ?? '10.8.0.2/32',
      isFavorite: json['isFavorite'] as bool? ?? false,
    );
  }

  /// Real ProtonVPN Servers
  static List<ServerModel> get sampleServers => const [
    ServerModel(
      id: 'us-free-72',
      name: 'United States - US-FREE#72',
      country: 'United States',
      countryCode: 'US',
      city: 'New York',
      flagEmoji: '🇺🇸',
      pingMs: 110,
      loadPercent: 68,
      isPremium: false,
      endpoint: '151.243.141.161:51820',
      publicKey: '2v1DSq+q5x9o7PMVUjJ6hSrBD4lfjevMp45E/1mgF2I=',
      privateKey: 'kLelmkL1hPeAP/HtpKCBr1hUxrCVrv8eW6UI8Lew63w=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'ca-free-23',
      name: 'Canada - CA-FREE#23',
      country: 'Canada',
      countryCode: 'CA',
      city: 'Toronto',
      flagEmoji: '🇨🇦',
      pingMs: 125,
      loadPercent: 47,
      isPremium: false,
      endpoint: '195.242.214.18:51820',
      publicKey: 'f2//rPIEgM2tb49le8jI/2O7XGub6O3iSIR2KGRBO34=',
      privateKey: 'SBHQNgTkZQdz5fkBsddDPnTdHehTaH0zT3UE7zOdXEY=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'jp-free-32',
      name: 'Japan - JP-FREE#32',
      country: 'Japan',
      countryCode: 'JP',
      city: 'Tokyo',
      flagEmoji: '🇯🇵',
      pingMs: 165,
      loadPercent: 39,
      isPremium: false,
      endpoint: '149.88.103.163:51820',
      publicKey: 'VrNJ8jPdfeaq1pB0rH9DvB/50Y8EW2MGn0uHOey1mxE=',
      privateKey: 'uBlFqZ4jprbi0+IF6fgO4mkVLx0vsf+yMjeNfbh5yGM=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'mx-free-13',
      name: 'Mexico - MX-FREE#13',
      country: 'Mexico',
      countryCode: 'MX',
      city: 'Mexico City',
      flagEmoji: '🇲🇽',
      pingMs: 140,
      loadPercent: 55,
      isPremium: false,
      endpoint: '84.20.27.44:51820',
      publicKey: 'rf3F9avKpfKKe+m6RA6y3PJyF4IU9KKkv8tYGcAziDE=',
      privateKey: '6PbqrKo6WqPAv304X+hMo0eeSVxQ76LNVRaOyw0+w3s=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'nl-free-220',
      name: 'Netherlands - NL-FREE#220',
      country: 'Netherlands',
      countryCode: 'NL',
      city: 'Amsterdam',
      flagEmoji: '🇳🇱',
      pingMs: 95,
      loadPercent: 41,
      isPremium: false,
      endpoint: '185.165.242.20:51820',
      publicKey: 'roBGyRXXwzJJwKeP6n1r8PwvW9FvOmPi4s1mKyWoM0A=',
      privateKey: '+EBwvcrOWxLwwepqF/Vco3cBZ3X6joXZVQ4oaeuSjH0=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'no-free-1',
      name: 'Norway - NO-FREE#1',
      country: 'Norway',
      countryCode: 'NO',
      city: 'Oslo',
      flagEmoji: '🇳🇴',
      pingMs: 105,
      loadPercent: 32,
      isPremium: false,
      endpoint: '95.173.205.163:51820',
      publicKey: '7fu30seb7WT0ViYGe/tkjNzqgJZM3hPa0QF0g/SXnQM=',
      privateKey: 'qGgSbSzUvcsuv7tLxtzEruNYTTTdJtzIPZeC3PKowmE=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'pl-free-1',
      name: 'Poland - PL-FREE#1',
      country: 'Poland',
      countryCode: 'PL',
      city: 'Warsaw',
      flagEmoji: '🇵🇱',
      pingMs: 85,
      loadPercent: 45,
      isPremium: false,
      endpoint: '149.102.244.97:51820',
      publicKey: 'ScCkMvpikYBB3IFtDJC6Xh59pmq4StGlU/JfvALPxUE=',
      privateKey: '4PMolXjM8X5YV5+NfONxu4tyR5lweUTDR1r1q+pmJGQ=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'ro-free-1',
      name: 'Romania - RO-FREE#1',
      country: 'Romania',
      countryCode: 'RO',
      city: 'Bucharest',
      flagEmoji: '🇷🇴',
      pingMs: 90,
      loadPercent: 35,
      isPremium: false,
      endpoint: '149.102.239.225:51820',
      publicKey: '5qZc9c0rHEKhBXd+NnQ69AJuYjCKqTjt1hM2+UaZDng=',
      privateKey: 'eAWwdHDTaa2vV67m0eYAh+KosMm2nKF6psGkj6W/em4=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'sg-free-1',
      name: 'Singapore - SG-FREE#1',
      country: 'Singapore',
      countryCode: 'SG',
      city: 'Singapore',
      flagEmoji: '🇸🇬',
      pingMs: 130,
      loadPercent: 55,
      isPremium: false,
      endpoint: '149.88.23.117:51820',
      publicKey: '7T/ncvn7/CYVSwHPpVJenUJKGEwIE6omzLZyNJ8mMEA=',
      privateKey: 'EO9K2mk952yW9vQN7RKvKnF/Xj1ecdfbnXkMKzavWlY=',
      clientIpv4: '10.2.0.2/32',
    ),
    ServerModel(
      id: 'ch-free-1',
      name: 'Switzerland - CH-FREE#1',
      country: 'Switzerland',
      countryCode: 'CH',
      city: 'Zurich',
      flagEmoji: '🇨🇭',
      pingMs: 80,
      loadPercent: 30,
      isPremium: false,
      endpoint: '138.199.6.181:51820',
      publicKey: 'kLP1kA+BuzvA6ecozP0c82I8u1aXkZmfMCxBZEqpNHY=',
      privateKey: 'cHMWsYMrJx4NjIHa6LBKpoZ9u/PxKbMDHJMcQ/72UWQ=',
      clientIpv4: '10.2.0.2/32',
    ),
  ];
}
